version: "2"
name: test-rs2
canonical: test-rs2
author: cycloidio
status: private
description: test
image: ""
keywords:
- fo
- provider:aws
technologies: []
dependencies: []
config:
  default:
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
    terraform:
      config:
        destination: ($ project $)/terraform/($ environment $)/config.tf
        path: terraform/default/config.tf.sample
      test-rs2:
        destination: ($ project $)/terraform/($ environment $)/test-rs2.tf
        path: terraform/default/test-rs2.tf.sample
