version: "2"
name: first-rs-develop
canonical: first-rs-develop
author: cycloidio
status: private
description: test after RS with develop
image: ""
keywords:
- foo
- bar
- provider:aws
technologies: []
dependencies: []
config:
  default:
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
    terraform:
      config:
        destination: ($ project $)/terraform/($ environment $)/config.tf
        path: terraform/default/config.tf.sample
      first-rs-develop:
        destination: ($ project $)/terraform/($ environment $)/first-rs-develop.tf
        path: terraform/default/first-rs-develop.tf.sample
