version: "2"
name: will fail.
canonical: will_fail
author: cycloidio
status: private
description: will fail.
image: https://cohire-image-bucket-2.s3.amazonaws.com/company/6216/-1609466507-identicon.png
keywords:
- will fail
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      will_fail:
        destination: ($ project $)/default/terraform/($ environment $)/will_fail.tf
        path: default/terraform/will_fail.tf.sample
