version: "2"
name: retryProjectImport
canonical: retryprojectimport
author: cycloidio
status: private
description: retryProjectImport
image: ""
keywords:
- retryProjectImport
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      retryprojectimport:
        destination: ($ project $)/default/terraform/($ environment $)/retryprojectimport.tf
        path: default/terraform/retryprojectimport.tf.sample
