version: "2"
name: temp stack
canonical: temp_stack
author: cycloidio
status: private
description: temp desc
image: ""
keywords:
- temp
- stack
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      temp_stack:
        destination: ($ project $)/default/terraform/($ environment $)/temp_stack.tf
        path: default/terraform/temp_stack.tf.sample
