version: "2"
name: rs7
canonical: rs7
author: cycloidio
status: private
description: rs7
image: ""
keywords:
- rs7
- provider:aws
technologies: []
dependencies: []
config:
  default:
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
    terraform:
      config:
        destination: ($ project $)/terraform/($ environment $)/config.tf
        path: terraform/default/config.tf.sample
      rs7:
        destination: ($ project $)/terraform/($ environment $)/rs7.tf
        path: terraform/default/rs7.tf.sample
