version: "2"
name: test stack
canonical: test_stack
author: cycloidio
status: private
description: test stack
image: ""
keywords:
- test stack
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      test_stack:
        destination: ($ project $)/default/terraform/($ environment $)/test_stack.tf
        path: default/terraform/test_stack.tf.sample
