version: "2"
name: debug2
canonical: debug2
author: cycloidio
status: private
description: debug2
image: ""
keywords:
- debug2
- provider:aws
technologies: []
dependencies: []
config:
  default:
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
