version: "2"
name: again
canonical: again
author: cycloidio
status: private
description: again
image: ""
keywords:
- again
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      again:
        destination: ($ project $)/default/terraform/($ environment $)/again.tf
        path: default/terraform/again.tf.sample
