version: "2"
name: my super awesome stack 2
canonical: my_super_awesome_stack_2
author: cycloidio
status: private
description: desc2
image: ""
keywords:
- key2
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
