#
# This file has been generated by Cycloid, please DO NOT modify.
# Any manual modifications done to this file, WILL be lost on the
# next project edition via the forms.
#
# Please note that comments in sample files will have been dropped
# due to some limitations upon files' generation.
#
# Any extra variables not found in the original file have been ignored.
#

module "rs7" {
  source = "./module-rs7"

  aws_instance_cycloid_bastion0_eu_we1_infra_ami               = "ami-e079f893"
  aws_instance_cycloid_bastion0_eu_we1_infra_availability_zone = "eu-west-1a"
}

