version: "2"
name: mystack1234
canonical: mystack1234
author: cycloidio
status: private
description: mystack1234
image: ""
keywords:
- mystack1234
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      mystack1234:
        destination: ($ project $)/default/terraform/($ environment $)/mystack1234.tf
        path: default/terraform/mystack1234.tf.sample
