#
# This file has been generated by Cycloid, please DO NOT modify.
# Any manual modifications done to this file, WILL be lost on the
# next project edition via the forms.
#
# Please note that comments in sample files will have been dropped
# due to some limitations upon files' generation.
#
# Any extra variables not found in the original file have been ignored.
#

module "nexus" {
  source = "./module-nexus"

  bastion_allowed_networks = [
    "0.0.0.0/0"
  ]
  bastion_instance_type = "t3a.micro"
  cidr                  = "10.0.0.0/16"
  customer              = var.customer
  env                   = var.env
  extra_tags = {
    demo                 = true
    monitoring_discovery = false
  }
  keypair_public       = var.keypair_public
  nexus_admin_password = "changeme"
  nexus_disk_size      = 20
  nexus_instance_type  = "t3a.medium"
  nexus_port           = "8081"
  private_subnets = [
    "10.0.1.0/24"
  ]
  project = var.project
  public_subnets = [
    "10.0.0.0/24"
  ]
}

