version: "2"
name: adadadad 2
canonical: adadadad
author: cycloidio
status: private
description: adadadad
image: https://avatars.githubusercontent.com/u/33682886?s=200&v=4
keywords:
- sd
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      adadadad:
        destination: ($ project $)/default/terraform/($ environment $)/adadadad.tf
        path: default/terraform/adadadad.tf.sample
