#
# This file has been generated by Cycloid, please DO NOT modify.
# Any manual modifications done to this file, WILL be lost on the
# next project edition via the forms.
#
# Please note that comments in sample files will have been dropped
# due to some limitations upon files' generation.
#
# Any extra variables not found in the original file have been ignored.
#

module "elk" {
  source = "./module-elk"

  allowed_secgroup                 = ""
  customer                         = var.customer
  env                              = var.env
  es_automated_snapshot_start_hour = 23
  es_instance_count                = 1
  es_instance_type                 = "t2.small.elasticsearch"
  es_version                       = "7.1"
  es_volume_size                   = 157
  es_zone_awareness_enabled        = false
  project                          = var.project
  subnet_ids = [
    "<subnet-ids>"
  ]
  vpc_id = "sdsd"
}

