version: "2"
name: aferaaa
canonical: aferaaa
author: cycloidio
status: private
description: aferaaa
image: ""
keywords:
- aferaaa
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      aferaaa:
        destination: ($ project $)/default/terraform/($ environment $)/aferaaa.tf
        path: default/terraform/aferaaa.tf.sample
