version: "2"
name: mystack2
canonical: mystack2
author: cycloidio
status: private
description: mystack2
image: ""
keywords:
- mystack2
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      mystack2:
        destination: ($ project $)/default/terraform/($ environment $)/mystack2.tf
        path: default/terraform/mystack2.tf.sample
