version: "2"
name: aadasda
canonical: aadasda
author: cycloidio
status: private
description: sdadsad
image: https://nodesk.co/remote-companies/assets/logos/_hu8848110923bfcd865a9e8efde66ef7c1_31887_5f377978ec117fa0bebd981415c1864f.png
keywords:
- asd
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      aadasda:
        destination: ($ project $)/default/terraform/($ environment $)/aadasda.tf
        path: default/terraform/aadasda.tf.sample
