version: "2"
name: longer name
canonical: longer_name
author: cycloidio
status: private
description: longer description
image: ""
keywords:
- keyworkd 1
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      longer_name:
        destination: ($ project $)/default/terraform/($ environment $)/longer_name.tf
        path: default/terraform/longer_name.tf.sample
