version: "2"
name: tired
canonical: tired
author: cycloidio
status: private
description: tired
image: ""
keywords:
- tired
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      tired:
        destination: ($ project $)/default/terraform/($ environment $)/tired.tf
        path: default/terraform/tired.tf.sample
