#
# This file has been generated by Cycloid, please DO NOT modify.
# Any manual modifications done to this file, WILL be lost on the
# next project edition via the forms.
#
# Please note that comments in sample files will have been dropped
# due to some limitations upon files' generation.
#
# Any extra variables not found in the original file have been ignored.
#
module "tf-vsphere" {
  source = "./module-vsphere"

  vm_cpu = 4

  vm_disk = 100

  vm_memory = 4096

  vm_name = "adadada"
}
