version: "2"
name: ace
canonical: ace
author: cycloidio
status: private
description: ace
image: https://avatars.githubusercontent.com/u/33682886?s=200&v=4
keywords:
- ace
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      ace:
        destination: ($ project $)/default/terraform/($ environment $)/ace.tf
        path: default/terraform/ace.tf.sample
