version: "2"
name: rs11
canonical: rs11
author: cycloidio
status: private
description: rs11
image: ""
keywords:
- rs11
- provider:aws
technologies: []
dependencies: []
config:
  default:
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
    terraform:
      config:
        destination: ($ project $)/terraform/($ environment $)/config.tf
        path: terraform/default/config.tf.sample
      rs11:
        destination: ($ project $)/terraform/($ environment $)/rs11.tf
        path: terraform/default/rs11.tf.sample
