version: "2"
name: chacha-stack
canonical: chacha-stack
author: cycloidio
status: private
description: chacha-stack
image: ""
keywords:
- chacha-stack
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      chacha-stack:
        destination: ($ project $)/default/terraform/($ environment $)/chacha-stack.tf
        path: default/terraform/chacha-stack.tf.sample
