version: "2"
name: adert
canonical: adert
author: cycloidio
status: private
description: adert
image: ""
keywords:
- adert
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      adert:
        destination: ($ project $)/default/terraform/($ environment $)/adert.tf
        path: default/terraform/adert.tf.sample
