#
# This file has been generated by Cycloid, please DO NOT modify.
# Any manual modifications done to this file, WILL be lost on the
# next project edition via the forms.
#
# Please note that comments in sample files will have been dropped
# due to some limitations upon files' generation.
#
# Any extra variables not found in the original file have been ignored.
#
api_login: ((raw_cyclobot-account.login))
api_password: ((raw_cyclobot-account.password))
approval_aws_access_key: ((aws_admin.access_key))
approval_aws_secret_key: ((aws_admin.secret_key))
aws_access_key: ((aws.access_key))
aws_default_region: eu-west-1
aws_secret_key: ((aws.secret_key))
config_git_branch: config
config_git_key: ((git_readonly.ssh_key))
config_git_repository: git@github.com:cycloidio/cycloid-stacks-test.git
config_terraform_path: testforms-dan3/terraform/dev
customer: seraf
env: dev
external_backend_aws_cred_name: aws
project: testforms-dan3
sc_branch: stacks
sc_git_key: ((git_readonly.ssh_key))
sc_path: stack-vsphere
sc_repository: git@github.com:cycloidio/cycloid-stacks-test.git
slack_hook: ((raw_slack-hooks.demo_channel))
terraform_storage_bucket_name: seraf-terraform-remote-state
terraform_storage_bucket_path: demo-testforms-dan3/dev
vsphere_password: ((aws_warnerbros))
vsphere_server: testformsdan3
vsphere_user: ((aws_warnerbros))
