---
default:
  pipeline:
    Radios:
      - widget: "radios"
        default: "M"
        unit: "EU t-shirt size"
        type: "map"
        values: [{label: XS, value: t3.micro}, {label: S, value: t3.small}, {label: M, value: t3.medium}, {label: L, value: t3.large}]
        description: ""
        key: "radio_mapped"
        name: "Mapped radio"
      - widget: "radios"
        default: 2
        unit: "score points"
        type: "integer"
        values: [1, 2, 3]
        description: ""
        key: "radio_integer"
        name: "Radio integer"
      - widget: "radios"
        default: false
        unit: "??"
        type: "boolean"
        values: [true, false]
        description: ""
        key: "radio_boolean"
        name: "Radio boolean"
      - widget: "radios"
        default: "kiwi"
        unit: "fruits"
        type: "string"
        values: ["banana", "mango", "strawberry", "kiwi"]
        description: ""
        key: "radio_strings"
        name: "Radio strings"
      - widget: "radios"
        default: [4, 5, 6]
        unit: "(???)"
        type: "array"
        values: [[1, 2, 3], [4, 5, 6]]
        description: ""
        key: "radio_array"
        name: "Radio array"

    Dropdown:
      - widget: "dropdown"
        default: "L"
        unit: "EU t-shirt size"
        type: "map"
        values: [{label: XS, value: t3.micro}, {label: S, value: t3.small}, {label: M, value: t3.medium}, {label: L, value: t3.large}]
        description: ""
        key: "dropdown_mapped"
        name: "Mapped dropdown"
      - widget: "dropdown"
        default: 2
        unit: "score points"
        type: "integer"
        values: [1, 2, 3]
        description: ""
        key: "dropdown_integer"
        name: "Dropdown integer"
      - widget: "dropdown"
        default: false
        unit: "??"
        type: "boolean"
        values: [true, false]
        description: ""
        key: "dropdown_boolean"
        name: "Dropdown boolean"
      - widget: "dropdown"
        default: "kiwi"
        unit: "fruits"
        type: "string"
        values: ["banana", "mango", "strawberry", "kiwi"]
        description: ""
        key: "dropdown_strings"
        name: "Dropdown strings"
      - widget: "dropdown"
        default: [4, 5, 6]
        unit: "(???)"
        type: "array"
        values: [[1, 2, 3], [4, 5, 6]]
        description: ""
        key: "dropdown_array"
        name: "Dropdown array"
      
    SliderList:
      - widget: "slider_list"
        required: false
        default: "S"
        unit: "EU t-shirt size"
        type: "map"
        values: [{label: XS, value: t3.micro}, {label: S, value: t3.small}, {label: M, value: t3.medium}, {label: L, value: t3.large}]
        description: ""
        key: "slider_list_mapped"
        name: "Mapped slider list"
      - widget: "slider_list"
        default: 2
        unit: "score points"
        type: "integer"
        values: [1, 2, 3]
        description: ""
        key: "slider_list_integer"
        name: "Slider list integer"
      - widget: "slider_list"
        default: false
        unit: "??"
        type: "boolean"
        values: [true, false]
        description: ""
        key: "slider_list_boolean"
        name: "Slider list boolean"
      - widget: "slider_list"
        default: "kiwi"
        unit: "fruits"
        type: "string"
        values: ["banana", "mango", "strawberry", "kiwi"]
        description: ""
        key: "slider_list_strings"
        name: "Slider list strings"

