version: "2"
name: mystack23
canonical: mystack23
author: cycloidio
status: private
description: mystack23
image: ""
keywords:
- mystack23
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      mystack23:
        destination: ($ project $)/default/terraform/($ environment $)/mystack23.tf
        path: default/terraform/mystack23.tf.sample
