module "mystack" {
  # aws_cloudfront_distribution_HMHeO_tags_Name                                           = "cycloidio-website-cloudfront-staging"
  # aws_cloudfront_distribution_HMHeO_tags_client                                         = "cycloid"
  # aws_cloudfront_distribution_HMHeO_tags_cycloid_io                                     = "true"
  # aws_cloudfront_distribution_HMHeO_tags_env                                            = "staging"
  # aws_cloudfront_distribution_HMHeO_tags_monitoring_discovery                           = "false"
  # aws_cloudfront_distribution_HMHeO_tags_project                                        = "cycloidio-website"
  # aws_cloudfront_distribution_HMHeO_tags_role                                           = "cdn"
  # aws_cloudfront_distribution_HMHeO_aliases                                                 = ["staging-cdn.cycloid.io"]
  # aws_cloudfront_distribution_HMHeO_comment                                                 = "cycloidio-website cdn on staging bucket"
  # aws_cloudfront_distribution_HMHeO_custom_error_response_error_code                        = 404
  # aws_cloudfront_distribution_HMHeO_default_cache_behavior_allowed_methods                  = ["POST", "GET", "HEAD", "PATCH", "DELETE", "OPTIONS", "PUT"]
  # aws_cloudfront_distribution_HMHeO_default_cache_behavior_cached_methods                   = ["GET", "HEAD"]
  # aws_cloudfront_distribution_HMHeO_default_cache_behavior_compress                         = true
  # aws_cloudfront_distribution_HMHeO_default_cache_behavior_default_ttl                      = 300
  # aws_cloudfront_distribution_HMHeO_default_cache_behavior_forwarded_values_cookies_forward = "none"
  # aws_cloudfront_distribution_HMHeO_default_cache_behavior_forwarded_values_query_string    = false
  # aws_cloudfront_distribution_HMHeO_default_cache_behavior_max_ttl                          = 1200
  # aws_cloudfront_distribution_HMHeO_default_cache_behavior_target_origin_id                 = "origin-bucket-cycloid-cycloidio-website-medias-staging"
  # aws_cloudfront_distribution_HMHeO_default_cache_behavior_viewer_protocol_policy           = "allow-all"
  # aws_cloudfront_distribution_HMHeO_enabled                                                 = true
  # aws_cloudfront_distribution_HMHeO_http_version                                            = "http2"
  # aws_cloudfront_distribution_HMHeO_is_ipv6_enabled                                         = true
  # aws_cloudfront_distribution_HMHeO_origin_domain_name                                      = "cycloid-cycloidio-website-medias-staging.s3.amazonaws.com"
  # aws_cloudfront_distribution_HMHeO_origin_origin_id                                        = "origin-bucket-cycloid-cycloidio-website-medias-staging"
  # aws_cloudfront_distribution_HMHeO_origin_s3_origin_config_origin_access_identity          = aws_cloudfront_origin_access_identity.QjMCN.cloudfront_access_identity_path
  # aws_cloudfront_distribution_HMHeO_price_class                                             = "PriceClass_200"
  # aws_cloudfront_distribution_HMHeO_restrictions_geo_restriction_restriction_type           = "none"
  # aws_cloudfront_distribution_HMHeO_tc_category                                             = "cloud_front"
  # aws_cloudfront_distribution_HMHeO_viewer_certificate_acm_certificate_arn                  = "arn:aws:acm:us-east-1:661913936052:certificate/31c46e72-b41a-40a1-9fa0-64b678545b59"
  # aws_cloudfront_distribution_HMHeO_viewer_certificate_minimum_protocol_version             = "TLSv1"
  # aws_cloudfront_distribution_HMHeO_viewer_certificate_ssl_support_method                   = "sni-only"
  # aws_cloudfront_distribution_HMHeO_wait_for_deployment                                     = true
  # aws_cloudfront_distribution_KjvvP_tags_Name                                           = "cycloidio-website-cloudfront-prod"
  # aws_cloudfront_distribution_KjvvP_tags_client                                         = "cycloid"
  # aws_cloudfront_distribution_KjvvP_tags_cycloid_io                                     = "true"
  # aws_cloudfront_distribution_KjvvP_tags_env                                            = "prod"
  # aws_cloudfront_distribution_KjvvP_tags_project                                        = "cycloidio-website"
  # aws_cloudfront_distribution_KjvvP_tags_role                                           = "cdn"
  # aws_cloudfront_distribution_KjvvP_aliases                                                 = ["cdn.cycloid.io"]
  # aws_cloudfront_distribution_KjvvP_comment                                                 = "cycloidio-website cdn on prod bucket"
  # aws_cloudfront_distribution_KjvvP_custom_error_response_error_code                        = 404
  # aws_cloudfront_distribution_KjvvP_default_cache_behavior_allowed_methods                  = ["POST", "GET", "HEAD", "PATCH", "DELETE", "OPTIONS", "PUT"]
  # aws_cloudfront_distribution_KjvvP_default_cache_behavior_cached_methods                   = ["GET", "HEAD"]
  # aws_cloudfront_distribution_KjvvP_default_cache_behavior_compress                         = true
  # aws_cloudfront_distribution_KjvvP_default_cache_behavior_default_ttl                      = 300
  # aws_cloudfront_distribution_KjvvP_default_cache_behavior_forwarded_values_cookies_forward = "none"
  # aws_cloudfront_distribution_KjvvP_default_cache_behavior_forwarded_values_query_string    = false
  # aws_cloudfront_distribution_KjvvP_default_cache_behavior_max_ttl                          = 1200
  # aws_cloudfront_distribution_KjvvP_default_cache_behavior_target_origin_id                 = "origin-bucket-cycloid-cycloidio-website-medias-prod"
  # aws_cloudfront_distribution_KjvvP_default_cache_behavior_viewer_protocol_policy           = "allow-all"
  # aws_cloudfront_distribution_KjvvP_enabled                                                 = true
  # aws_cloudfront_distribution_KjvvP_http_version                                            = "http2"
  # aws_cloudfront_distribution_KjvvP_is_ipv6_enabled                                         = true
  # aws_cloudfront_distribution_KjvvP_origin_domain_name                                      = "cycloid-cycloidio-website-medias-prod.s3.amazonaws.com"
  # aws_cloudfront_distribution_KjvvP_origin_origin_id                                        = "origin-bucket-cycloid-cycloidio-website-medias-prod"
  # aws_cloudfront_distribution_KjvvP_origin_s3_origin_config_origin_access_identity          = aws_cloudfront_origin_access_identity.oUtQS.cloudfront_access_identity_path
  # aws_cloudfront_distribution_KjvvP_price_class                                             = "PriceClass_200"
  # aws_cloudfront_distribution_KjvvP_restrictions_geo_restriction_restriction_type           = "none"
  # aws_cloudfront_distribution_KjvvP_tc_category                                             = "cloud_front"
  # aws_cloudfront_distribution_KjvvP_viewer_certificate_acm_certificate_arn                  = "arn:aws:acm:us-east-1:661913936052:certificate/31c46e72-b41a-40a1-9fa0-64b678545b59"
  # aws_cloudfront_distribution_KjvvP_viewer_certificate_minimum_protocol_version             = "TLSv1"
  # aws_cloudfront_distribution_KjvvP_viewer_certificate_ssl_support_method                   = "sni-only"
  # aws_cloudfront_distribution_KjvvP_wait_for_deployment                                     = true
  # aws_cloudfront_origin_access_identity_QjMCN_comment                                       = "medias bucket staging"
  # aws_cloudfront_origin_access_identity_QjMCN_tc_category                                   = "cloud_front"
  # aws_cloudfront_origin_access_identity_iVkvV_comment                                       = "Youdeploy frontend preprod"
  # aws_cloudfront_origin_access_identity_iVkvV_tc_category                                   = "cloud_front"
  # aws_cloudfront_origin_access_identity_oUtQS_comment                                       = "medias bucket prod"
  # aws_cloudfront_origin_access_identity_oUtQS_tc_category                                   = "cloud_front"
  source = "module-mystack"
}

