version: "2"
name: ii-debug
canonical: ii-debug
author: cycloidio
status: private
description: ii-debug
image: ""
keywords:
- ii-debug
- provider:aws
technologies: []
dependencies: []
config:
  default:
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
