version: "2"
name: tres
canonical: tres
author: cycloidio
status: private
description: cuatros
image: ""
keywords:
- tres
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      tres:
        destination: ($ project $)/default/terraform/($ environment $)/tres.tf
        path: default/terraform/tres.tf.sample
