version: "2"
name: rs4
canonical: rs4
author: cycloidio
status: private
description: rs4
image: ""
keywords:
- rs4
- provider:aws
technologies: []
dependencies: []
config:
  default:
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
