version: "2"
name: adsasdasdasd
canonical: adsasdasdasd
author: cycloidio
status: private
description: asdasdasd
image: ""
keywords:
- asdasd
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      adsasdasdasd:
        destination: ($ project $)/default/terraform/($ environment $)/adsasdasdasd.tf
        path: default/terraform/adsasdasdasd.tf.sample
