version: "2"
name: perrfecto
canonical: perrfecto
author: cycloidio
status: private
description: perrfecto
image: https://www.cycloid.io/themes/cycloid/images/owl_logo.png
keywords:
- perrfecto
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      perrfecto:
        destination: ($ project $)/default/terraform/($ environment $)/perrfecto.tf
        path: default/terraform/perrfecto.tf.sample
