version: "2"
name: new name for stackk
canonical: afafaffa
author: cycloidio
status: private
description: edited again lalal
image: https://www.gravatar.com/avatar/efef01b733b5e8af2d8670efe6990e90?s=256&d=identicon&r=PG
keywords:
- afafaffa
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      afafaffa:
        destination: ($ project $)/default/terraform/($ environment $)/afafaffa.tf
        path: default/terraform/afafaffa.tf.sample
