version: "2"
name: new name for stack
canonical: afafaffa
author: cycloidio
status: private
description: edited again lala
image: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now
keywords:
- afafaffa
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      afafaffa:
        destination: ($ project $)/default/terraform/($ environment $)/afafaffa.tf
        path: default/terraform/afafaffa.tf.sample
