version: "2"
name: tresset
canonical: tresset
author: cycloidio
status: private
description: tresset
image: ""
keywords:
- tresset
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      tresset:
        destination: ($ project $)/default/terraform/($ environment $)/tresset.tf
        path: default/terraform/tresset.tf.sample
