first-usecase:
  pipeline:
    SimpleText:
    - widget: "simple_text"
      required: true
      default: "test"
      type: "string"
      description: "key: simple_text_string"
      key: "simple_text_string"
      name: "SimpleText (String)"
    Switch:
    - widget: "switch"
      required: true
      default: true
      type: "boolean"
      description: "key: switch_boolean"
      key: "switch_boolean"
      name: "Switch (Boolean)"
    Number:
    - widget: "number"
      required: true
      default: 12
      type: "integer"
      description: "key: number_integer"
      key: "number_integer"
      name: "Number (Integer)"
    AutoComplete:
    - widget: "auto_complete"
      required: true
      type: "string"
      default: "test"
      values: ["un", "dos", "tres", "test"]
      description: "key: autocomplete_string"
      key: "autocomplete_string"
      name: "Autocomplete (String)"
    SliderRange:
    - widget: "slider_range"
      required: true
      default: 15
      type: "integer"
      unit: "Ghz"
      values: [0, 60]
      description: "key: slider_range_integer"
      key: "slider_range_integer"
      name: "SliderRange (Integer)"
    SliderList:
    - widget: "slider_list"
      required: true
      type: "string"
      default: "tres"
      values: ["un", "dos", "tres", "cuatro", "cinco", "cincoytrecuartos", "quinientomilseicientocinquentacinco"]
      description: "key: slider_list_string"
      key: "slider_list_string"
      name: "Slider List (String)"
    - widget: "slider_list"
      required: true
      type: "boolean"
      default: false
      values: [true, false]
      description: "key: slider_list_boolean"
      key: "slider_list_boolean"
      name: "Slider List (Boolean)"
    - widget: "slider_list"
      required: true
      type: "integer"
      default: 4
      values: [2, 4, 6, 8, 10]
      description: "key: slider_list_integer"
      key: "slider_list_integer"
      name: "Slider List (Integer)"
    Textarea:
    - widget: "text_area"
      required: true
      default: "extra info here"
      unit: "simple words"
      type: "string"
      description: "key: text_area_string"
      key: "text_area_string"
      name: "Textarea (String)"
    - widget: "text_area"
      required: true
      default: 3
      type: "integer"
      description: "key: text_area_integer"
      key: "text_area_integer"
      name: "Textarea (Integer)"
    - widget: "text_area"
      required: true
      default: false
      type: "boolean"
      description: "key: text_area_boolean"
      key: "text_area_boolean"
      name: "Textarea (Boolean)"
    - widget: "text_area"
      required: true
      default: [4, 5, 6]
      type: "array"
      description: "key: text_area_array"
      key: "text_area_array"
      name: "Textarea (Array)"
    - widget: "text_area"
      required: true
      default: { myvar3: 3 }
      type: "map"
      description: "key: text_area_map"
      key: "text_area_map"
      name: "Textarea (Map)"
    Dropdown:
    - widget: "dropdown"
      required: true
      values: ["un", "dos", "tres"]
      default: "tres"
      type: "string"
      description: "key: dropdown_string"
      key: "dropdown_string"
      name: "Dropdown (String)"
    - widget: "dropdown"
      required: true
      values: [1, 2, 3]
      default: 3
      type: "integer"
      description: "key: dropdown_integer"
      key: "dropdown_integer"
      name: "Dropdown (Integer)"
    - widget: "dropdown"
      required: true
      values: [true, false]
      default: false
      type: "boolean"
      description: "key: dropdown_boolean"
      key: "dropdown_boolean"
      name: "Dropdown (Boolean)"
    - widget: "dropdown"
      required: true
      values: [[1, 2, 3], [4, 5, 6], ["a", "b", "c"]]
      default: [4, 5, 6]
      type: "array"
      description: "key: dropdown_array"
      key: "dropdown_array"
      name: "Dropdown (Array)"
    - widget: "dropdown"
      required: true
      values: [{ myvar: 'key' }, { myvar2: true }, { myvar3: 3 }]
      default: { myvar3: 3 }
      type: "map"
      description: "key: dropdown_map"
      key: "dropdown_map"
      name: "Dropdown (Map)"
    Radios:
    - widget: "radios"
      required: true
      values: ["un", "dos", "tres", "cuatro", "cinco", "cincoytrecuartos", "quinientomilseicientocinquentacinco", "ciclicing again", "un", "dos", "tres", "cuatro", "cinco", "cincoytrecuartos", "quinientomilseicientocinquentacinco"]
      default: "tres"
      type: "string"
      description: "key: radios_string"
      key: "radios_string"
      name: "Radios (String)"
    - widget: "radios"
      required: true
      values: [1, 2, 3]
      default: 3
      type: "integer"
      description: "key: radios_integer"
      key: "radios_integer"
      name: "Radios (Integer)"
    - widget: "radios"
      required: true
      values: [true, false]
      default: false
      type: "boolean"
      description: "key: radios_boolean"
      key: "radios_boolean"
      name: "Radios (Boolean)"
    - widget: "radios"
      required: true
      values: [[1, 2, 3], [4, 5, 6], ["a", "b", "c"]]
      default: [4, 5, 6]
      type: "array"
      description: "key: radios_array"
      key: "radios_array"
      name: "Radios (Array)"
    - widget: "radios"
      required: true
      values: [{ myvar: 'key' }, { myvar2: true }, { myvar3: 3 }]
      default: { myvar3: 3 }
      type: "map"
      description: "key: radios_map"
      key: "radios_map"
      name: "Radios (Map)"
    Credentials:
    - widget: "cy_cred"
      required: true
      default: "((aws_my_aws.secret_key))"
      type: "string"
      description: "key: cred_string"
      key: "cred_string"
      name: "Credentials (String)"
    Stacks, ConfigRepository and Branch:
    - widget: "cy_scs"
      required: true
      default: "git@github.com:dangzo/sc-test.git"
      type: "string"
      description: "key: scs_string"
      key: "scs_string"
      name: "Stacks (String)"
    - widget: "cy_crs"
      required: true
      default: "git@github.com:dangzo/sc-test.git"
      type: "string"
      description: "key: crs_string"
      key: "crs_string"
      name: "Config Repository (String)"
    - widget: "cy_branch"
      required: true
      default: "stacks-staging"
      type: "string"
      description: "key: branch_crs_string"
      key: "branch_crs_string"
      name: "Branch CR (String)"
      source: "crs_string"
    - widget: "cy_branch"
      required: true
      default: "config-staging"
      type: "string"
      description: "key: branch_scs_string"
      key: "branch_scs_string"
      name: "Branch Stacks (String)"
      source: "scs_string"
second-usecase:
  pipeline:
    default:
    - widget: "simple_text"
      type: "string"
      required: true
      description: "prv_subnet_id"
      key: "prv_subnet_id"
      name: "prv_subnet_id"
    - widget: "simple_text"
      type: "string"
      description: "vpc_identifier"
      key: "vpc_identifier"
      name: "vpc_identifier"
    - widget: "simple_text"
      type: "string"
      required: true
      description: "rds_pwd"
      key: "rds_pwd"
      name: "rds_pwd"
    - widget: "simple_text"
      type: "string"
      description: "prv_subnet_id2"
      key: "prv_subnet_id2"
      name: "prv_subnet_id2"
    - widget: "simple_text"
      type: "string"
      description: "vpc_identifier2"
      key: "vpc_identifier2"
      name: "vpc_identifier2"
    - widget: "simple_text"
      type: "string"
      description: "rds_pwd2"
      key: "rds_pwd2"
      name: "rds_pwd2"
    - widget: "simple_text"
      type: "string"
      description: "prv_subnet_id3"
      key: "prv_subnet_id3"
      name: "prv_subnet_id3"
    - widget: "simple_text"
      type: "string"
      description: "vpc_identifier3"
      key: "vpc_identifier3"
      name: "vpc_identifier3"
    - widget: "simple_text"
      type: "string"
      description: "rds_pwd3"
      key: "rds_pwd3"
      name: "rds_pwd3"
    - widget: "simple_text"
      type: "string"
      description: "prv_subnet_id4"
      key: "prv_subnet_id4"
      name: "prv_subnet_id4"
    - widget: "simple_text"
      type: "string"
      description: "vpc_identifier4"
      key: "vpc_identifier4"
      name: "vpc_identifier4"
    - widget: "simple_text"
      type: "string"
      description: "rds_pwd4"
      key: "rds_pwd4"
      name: "rds_pwd4"
  terraform:
    default:
    - widget: "simple_text"
      type: "string"
      required: true
      description: "private_subnet_id"
      key: "private_subnet_id"
      name: "private_subnet_id"
    - widget: "simple_text"
      type: "string"
      required: true
      description: "vpc_id"
      key: "vpc_id"
      name: "vpc_id"
    - widget: "simple_text"
      type: "string"
      description: "rds_password"
      key: "rds_password"
      name: "rds_password"
    - widget: "simple_text"
      type: "string"
      description: "private_subnet_id2"
      key: "private_subnet_id2"
      name: "private_subnet_id2"
    - widget: "simple_text"
      type: "string"
      description: "vpc_id2"
      key: "vpc_id2"
      name: "vpc_id2"
    - widget: "simple_text"
      type: "string"
      description: "rds_password2"
      key: "rds_password2"
      name: "rds_password2"
    - widget: "simple_text"
      type: "string"
      description: "private_subnet_id3"
      key: "private_subnet_id3"
      name: "private_subnet_id3"
    - widget: "simple_text"
      type: "string"
      description: "vpc_id3"
      key: "vpc_id3"
      name: "vpc_id3"
    - widget: "simple_text"
      type: "string"
      description: "rds_password3"
      key: "rds_password3"
      name: "rds_password3"
    - widget: "simple_text"
      type: "string"
      description: "private_subnet_id4"
      key: "private_subnet_id4"
      name: "private_subnet_id4"
    - widget: "simple_text"
      type: "string"
      description: "vpc_id4"
      key: "vpc_id4"
      name: "vpc_id4"
    - widget: "simple_text"
      type: "string"
      description: "rds_password4"
      key: "rds_password4"
      name: "rds_password4"