version: "2"
name: Stacked Stack
canonical: stacked_stack
author: cycloidio
status: private
description: 'Stacked '
image: https://i.stack.imgur.com/1Bds0.png
keywords:
- Stacked Stack
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      stacked_stack:
        destination: ($ project $)/default/terraform/($ environment $)/stacked_stack.tf
        path: default/terraform/stacked_stack.tf.sample
