version: "2"
name: new stack
canonical: new_stack
author: cycloidio
status: private
description: new stack
image: ""
keywords:
- new stack
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
