version: "2"
name: artemis
canonical: artemis
author: cycloidio
status: private
description: artemis
image: ""
keywords:
- artemis
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      artemis:
        destination: ($ project $)/default/terraform/($ environment $)/artemis.tf
        path: default/terraform/artemis.tf.sample
