version: "2"
name: Magento123
canonical: magento123
author: cycloidio
status: private
description: Magento123
image: ""
keywords:
- Magento123
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      magento123:
        destination: ($ project $)/default/terraform/($ environment $)/magento123.tf
        path: default/terraform/magento123.tf.sample
