version: "2"
name: rs10
canonical: rs10
author: cycloidio
status: private
description: rs10
image: ""
keywords:
- rs10
- provider:aws
technologies: []
dependencies: []
config:
  default:
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
