version: "2"
name: eu-west-1
canonical: eu-west-1
author: cycloidio
status: private
description: eu-west-1
image: ""
keywords:
- eu-west-1
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
